# Generated by Django 3.2.5 on 2023-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
