# Generated by Django 3.2.5 on 2021-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
